/* tslint:disable */
// Do not edit this file.
// This file is generated by the C# API

// About this-keyword and <T> in it see: https://github.com/Microsoft/TypeScript/issues/6452

import { request } from "request";

export interface ApiErrors {
    onError<T>(this: T, errorCode: "Forbidden", cb: (data: null, req?: T) => void): T;
    onError<T>(this: T, errorCode: "NotFound", cb: (data: null, req?: T) => void): T;
    onError<T>(this: T, errorCode: "ValidationError", cb: (data: { fields : { [k: string]: { code : string, message : string, data : {  } }[] }, general : { code : string, message : string, data : {  } }[] }, req?: T) => void): T;
}
export const Api = {
    Account : {
        Claims : () =>
            request<void>(`Account/Claims`, "GET", null, null),
        LoggedIn : () =>
            request<{ id : number, email : string }>(`Account/LoggedIn`, "GET", null, null)
    }
};
